### ISSUE TITLE
Windows 11 IoT (Enterprise) GpioController support

### ISSUE THREAD

**Issue by nietras** [LattePandaTeam/LattePanda-Mu#13]
Trying to use .NET/UWP `GpioController` for GPIO on Latte Panda Mu with Full Carrier Board on Windows 11 IoT Enterprise (x64), but this appears to fail:
```
Unhandled exception. System.NotSupportedException: No GPIO controllers exist on this system.
   at System.Device.Gpio.Drivers.Windows10Driver..ctor()
   at System.Device.Gpio.GpioController.GetBestDriverForBoardOnWindows()
   at System.Device.Gpio.GpioController.GetBestDriverForBoard()
   at System.Device.Gpio.GpioController..ctor(PinNumberingScheme numberingScheme)
   at System.Device.Gpio.GpioController..ctor()
   at Program.<Main>$(String[] args) in C:\Users\Niels\source\repos\GpioDemo\Program.cs:line 7
   at Program.<Main>(String[] args)
```
e.g. with simple code like:
```
new System.Device.Gpio.GpioController()
```
I have installed drivers as found here in this github repo and device manager shows the following for system devices. Maybe something is missing or?

Or how can I use the GPIO from .NET 8/9 in Windows?

![image](https://github.com/user-attachments/assets/2f1d8d11-d44b-43dd-902a-d7f1622d8d80)

**Comment by An-nym-us** [comment]
the GPIO pins are not yet supported but you can use the I2c and the uart stuff.

**Comment by nietras** [comment]
That is unfortunate, since we solely bought the LattePanda expecting Gpio to work? When is this expected to be working and what are the pre-requisites for this to work?

**Comment by jgqoc** [comment]
sadly i'm not sure when they will release a bios with the gpio pins working. Now you can use the I2C and UART. As of right now i'm using the I2c's. You can use a i2c to GPIO expander. I have 12 different sensors and multiple relays hooked up to one i2c port.

**Comment by jgqoc** [comment]
I was in the same boat, purchased it for the gpio but i've that the I2c  (though i do need more external hardware) actually exceeds what i need and it works very well.
